const $=s=>document.querySelector(s);const preview=$('#preview'),canvas=$('#canvas'),emptyState=$('#emptyState'),statusEl=$('#status'),recordingBadge=$('#recordingBadge'),countdownEl=$('#countdown'),gridOverlay=$('#gridOverlay'),gallery=$('#gallery');const startBtn=$('#startBtn'),captureBtn=$('#captureBtn'),recordBtn=$('#recordBtn'),switchBtn=$('#switchBtn'),clearBtn=$('#clearBtn'),zoomRange=$('#zoomRange'),zoomValue=$('#zoomValue'),gridToggle=$('#gridToggle'),stampToggle=$('#stampToggle'),locationToggle=$('#locationToggle'),timerSelect=$('#timerSelect');let stream=null,facingMode='environment',recorder=null,recordedChunks=[],captures=[],videoTrack=null,currentLocation=null;
function setStatus(m){statusEl.textContent=m}function cameraAvailable(){return!!(navigator.mediaDevices&&navigator.mediaDevices.getUserMedia)}
async function stopCamera(){if(recorder?.state==='recording')recorder.stop();stream?.getTracks().forEach(t=>t.stop());stream=null;videoTrack=null;preview.srcObject=null;emptyState.hidden=false;captureBtn.disabled=recordBtn.disabled=switchBtn.disabled=true;zoomRange.disabled=true;startBtn.textContent='Start Camera';setStatus('Camera off')}
function setupZoom(){videoTrack=stream?.getVideoTracks()[0]||null;const caps=videoTrack?.getCapabilities?.()||{};if(!caps.zoom){zoomRange.min=zoomRange.max=zoomRange.value=1;zoomValue.textContent='1.0×';zoomRange.disabled=true;return}zoomRange.min=caps.zoom.min;zoomRange.max=caps.zoom.max;zoomRange.step=caps.zoom.step||.1;zoomRange.value=videoTrack.getSettings().zoom||caps.zoom.min;zoomValue.textContent=`${Number(zoomRange.value).toFixed(1)}×`;zoomRange.disabled=false}
async function startCamera(){if(!cameraAvailable()){setStatus('Camera unsupported');alert('Try Chrome or Safari over HTTPS.');return}if(stream){await stopCamera();return}try{setStatus('Opening camera…');stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:facingMode},width:{ideal:3840},height:{ideal:2160}},audio:true});preview.srcObject=stream;await preview.play();emptyState.hidden=true;captureBtn.disabled=false;recordBtn.disabled=typeof MediaRecorder==='undefined';switchBtn.disabled=false;startBtn.textContent='Stop Camera';setupZoom();setStatus('Camera ready')}catch(e){console.error(e);stream=null;setStatus('Permission needed');alert('Allow camera and microphone permission, then tap Start Camera again.') }}
async function switchCamera(){if(!stream)return;stream.getTracks().forEach(t=>t.stop());stream=null;facingMode=facingMode==='environment'?'user':'environment';await startCamera()}
async function getLocation(){if(!locationToggle.checked)return null;if(currentLocation)return currentLocation;setStatus('Getting location…');return new Promise(resolve=>navigator.geolocation?.getCurrentPosition(p=>{currentLocation={lat:p.coords.latitude,lon:p.coords.longitude};resolve(currentLocation)},()=>{setStatus('Location unavailable');resolve(null)},{enableHighAccuracy:true,timeout:8000,maximumAge:60000})||resolve(null))}
function addCapture(blob,type,extension){const url=URL.createObjectURL(blob),stamp=new Date().toISOString().replace(/[:.]/g,'-');captures.unshift({url,type,filename:`osko-${type}-${stamp}.${extension}`});renderGallery()}
function drawStamp(ctx,w,h,location){const lines=[];if(stampToggle.checked)lines.push(new Date().toLocaleString());if(location)lines.push(`${location.lat.toFixed(6)}, ${location.lon.toFixed(6)}`);if(!lines.length)return;const size=Math.max(24,Math.round(w/45)),pad=Math.round(size*.65),lineHeight=Math.round(size*1.25),boxH=lines.length*lineHeight+pad*2;ctx.font=`600 ${size}px system-ui`;ctx.textBaseline='top';ctx.fillStyle='rgba(0,0,0,.62)';ctx.fillRect(0,h-boxH,w,boxH);ctx.fillStyle='#fff';lines.forEach((line,i)=>ctx.fillText(line,pad,h-boxH+pad+i*lineHeight))}
async function captureNow(){if(!stream||!preview.videoWidth)return;const location=await getLocation();canvas.width=preview.videoWidth;canvas.height=preview.videoHeight;const ctx=canvas.getContext('2d');ctx.drawImage(preview,0,0,canvas.width,canvas.height);drawStamp(ctx,canvas.width,canvas.height,location);canvas.toBlob(blob=>{if(blob){addCapture(blob,'photo','jpg');setStatus('Photo captured')}},'image/jpeg',.96)}
async function takePhoto(){const seconds=Number(timerSelect.value);captureBtn.disabled=true;if(seconds){for(let i=seconds;i>0;i--){countdownEl.hidden=false;countdownEl.textContent=i;setStatus(`Photo in ${i}`);await new Promise(r=>setTimeout(r,1000))}countdownEl.hidden=true}await captureNow();captureBtn.disabled=false}
function bestVideoMimeType(){return['video/webm;codecs=vp9,opus','video/webm;codecs=vp8,opus','video/webm','video/mp4'].find(t=>MediaRecorder.isTypeSupported(t))||''}
function toggleRecording(){if(!stream||typeof MediaRecorder==='undefined')return;if(recorder?.state==='recording'){recorder.stop();return}recordedChunks=[];const mimeType=bestVideoMimeType();recorder=new MediaRecorder(stream,mimeType?{mimeType}:undefined);recorder.ondataavailable=e=>{if(e.data.size)recordedChunks.push(e.data)};recorder.onstop=()=>{const type=recorder.mimeType||'video/webm',ext=type.includes('mp4')?'mp4':'webm';addCapture(new Blob(recordedChunks,{type}),'video',ext);recordingBadge.hidden=true;recordBtn.textContent='Record Video';recordBtn.classList.remove('danger');setStatus('Video saved')};recorder.start(1000);recordingBadge.hidden=false;recordBtn.textContent='Stop Recording';recordBtn.classList.add('danger');setStatus('Recording')}
function removeCapture(i){URL.revokeObjectURL(captures[i].url);captures.splice(i,1);renderGallery()}function renderGallery(){gallery.innerHTML='';if(!captures.length){gallery.innerHTML='<p class="gallery-empty">Photos and videos will appear here.</p>';return}captures.forEach((c,i)=>{const card=document.createElement('article');card.className='capture-item';const media=c.type==='photo'?`<img src="${c.url}" alt="OSKO camera capture">`:`<video src="${c.url}" controls playsinline></video>`;card.innerHTML=`${media}<div class="capture-actions"><a href="${c.url}" download="${c.filename}">Save</a><button type="button" data-remove="${i}">Delete</button></div>`;gallery.appendChild(card)})}
startBtn.addEventListener('click',startCamera);captureBtn.addEventListener('click',takePhoto);recordBtn.addEventListener('click',toggleRecording);switchBtn.addEventListener('click',switchCamera);gridToggle.addEventListener('change',()=>gridOverlay.hidden=!gridToggle.checked);zoomRange.addEventListener('input',async()=>{zoomValue.textContent=`${Number(zoomRange.value).toFixed(1)}×`;try{await videoTrack?.applyConstraints({advanced:[{zoom:Number(zoomRange.value)}]})}catch(e){console.warn(e)}});locationToggle.addEventListener('change',()=>{if(!locationToggle.checked)currentLocation=null});clearBtn.addEventListener('click',()=>{captures.forEach(c=>URL.revokeObjectURL(c.url));captures=[];renderGallery()});gallery.addEventListener('click',e=>{const b=e.target.closest('[data-remove]');if(b)removeCapture(Number(b.dataset.remove))});window.addEventListener('beforeunload',()=>stream?.getTracks().forEach(t=>t.stop()));if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(console.error));if(!cameraAvailable())setStatus('Camera unsupported');
