const $=s=>document.querySelector(s);
const preview=$('#preview'),canvas=$('#canvas'),cameraCard=$('#cameraCard'),emptyState=$('#emptyState'),statusEl=$('#status'),recordingBadge=$('#recordingBadge'),countdownEl=$('#countdown'),gridOverlay=$('#gridOverlay'),gallery=$('#gallery'),errorBox=$('#errorBox');
const startBtn=$('#startBtn'),captureBtn=$('#captureBtn'),recordBtn=$('#recordBtn'),switchBtn=$('#switchBtn'),quickCaptureBtn=$('#quickCaptureBtn'),quickSwitchBtn=$('#quickSwitchBtn'),quickRecordBtn=$('#quickRecordBtn'),fullscreenBtn=$('#fullscreenBtn'),dockStart=$('#dockStart'),dockPhoto=$('#dockPhoto'),dockVideo=$('#dockVideo'),dockSwitch=$('#dockSwitch'),nativeCapture=$('#nativeCapture'),clearBtn=$('#clearBtn');
const zoomRange=$('#zoomRange'),zoomValue=$('#zoomValue'),brightnessRange=$('#brightnessRange'),brightnessValue=$('#brightnessValue'),nightToggle=$('#nightToggle'),torchToggle=$('#torchToggle'),gridToggle=$('#gridToggle'),stampToggle=$('#stampToggle'),locationToggle=$('#locationToggle'),timerSelect=$('#timerSelect');
let stream=null,videoTrack=null,facingMode='environment',recorder=null,recordedChunks=[],captures=[],countdownRunning=false,currentLocation=null;

function setStatus(m){statusEl.textContent=m}
function showError(m=''){errorBox.hidden=!m;errorBox.textContent=m}
function cameraAvailable(){return Boolean(navigator.mediaDevices?.getUserMedia)}
function resetCountdown(){countdownRunning=false;countdownEl.hidden=true;countdownEl.textContent=''}
function setEnabled(on){[captureBtn,quickCaptureBtn,dockPhoto,switchBtn,quickSwitchBtn,dockSwitch].forEach(b=>b.disabled=!on);const vr=on&&typeof MediaRecorder!=='undefined';[recordBtn,quickRecordBtn,dockVideo].forEach(b=>b.disabled=!vr);startBtn.textContent=dockStart.textContent=on?'Stop':'Start'}
function lightValues(){const b=Number(brightnessRange.value)/100,c=nightToggle.checked?1.24:1.08,s=nightToggle.checked?1.16:1.03;return{b,c,s}}
function updateLight(){const{b,c,s}=lightValues();preview.style.filter=`brightness(${b}) contrast(${c}) saturate(${s})`;brightnessValue.textContent=`${brightnessRange.value}%`}

async function setTorch(on){if(!videoTrack)return;try{await videoTrack.applyConstraints({advanced:[{torch:on}]});torchToggle.checked=on;setStatus(on?'Flashlight on':'Flashlight off')}catch(e){torchToggle.checked=false;torchToggle.disabled=true;showError('This camera does not allow flashlight control in Chrome.');setStatus('Flashlight unavailable')}}

function setupCapabilities(){videoTrack=stream?.getVideoTracks()[0]||null;const caps=videoTrack?.getCapabilities?.()||{};if(caps.zoom){zoomRange.min=caps.zoom.min;zoomRange.max=caps.zoom.max;zoomRange.step=caps.zoom.step||.1;zoomRange.value=videoTrack.getSettings().zoom||caps.zoom.min;zoomRange.disabled=false}else{zoomRange.min=zoomRange.max=zoomRange.value=1;zoomRange.disabled=true}zoomValue.textContent=`${Number(zoomRange.value).toFixed(1)}×`;torchToggle.disabled=!caps.torch;torchToggle.checked=false}

async function stopCamera(){resetCountdown();if(recorder?.state==='recording')recorder.stop();if(torchToggle.checked)await setTorch(false);stream?.getTracks().forEach(t=>t.stop());stream=null;videoTrack=null;preview.srcObject=null;emptyState.hidden=false;zoomRange.disabled=true;torchToggle.disabled=true;setEnabled(false);setStatus('Camera off')}

async function startCamera(){showError('');if(stream){await stopCamera();return}if(!cameraAvailable()){showError('Live camera is unavailable here. Tap “Use Phone Camera” below.');setStatus('Use phone camera');return}try{setStatus('Opening camera…');stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:facingMode},width:{ideal:3840},height:{ideal:2160}},audio:true});preview.srcObject=stream;await preview.play();emptyState.hidden=true;setupCapabilities();setEnabled(true);updateLight();setStatus('Camera ready')}catch(e){console.error(e);stream=null;setEnabled(false);const reason=e?.name==='NotAllowedError'?'Camera or microphone permission is blocked. Allow permission in Chrome, then tap Start again.':'The live camera could not start. Use the Phone Camera button as a reliable fallback.';showError(reason);setStatus('Camera blocked')}}

async function switchCamera(){if(!stream)return;resetCountdown();stream.getTracks().forEach(t=>t.stop());stream=null;videoTrack=null;facingMode=facingMode==='environment'?'user':'environment';await startCamera()}

async function getLocation(){if(!locationToggle.checked)return null;if(currentLocation)return currentLocation;return new Promise(resolve=>{if(!navigator.geolocation){resolve(null);return}navigator.geolocation.getCurrentPosition(p=>{currentLocation={lat:p.coords.latitude,lon:p.coords.longitude};resolve(currentLocation)},()=>resolve(null),{enableHighAccuracy:true,timeout:7000,maximumAge:60000})})}
function addCapture(blob,type,ext){const url=URL.createObjectURL(blob),stamp=new Date().toISOString().replace(/[:.]/g,'-');captures.unshift({url,type,filename:`osko-${type}-${stamp}.${ext}`});renderGallery()}
function drawStamp(ctx,w,h,loc){const lines=[];if(stampToggle.checked)lines.push(new Date().toLocaleString());if(loc)lines.push(`${loc.lat.toFixed(6)}, ${loc.lon.toFixed(6)}`);if(!lines.length)return;const size=Math.max(24,Math.round(w/45)),pad=Math.round(size*.65),lh=Math.round(size*1.25),box=lines.length*lh+pad*2;ctx.font=`600 ${size}px system-ui`;ctx.textBaseline='top';ctx.fillStyle='rgba(0,0,0,.62)';ctx.fillRect(0,h-box,w,box);ctx.fillStyle='#fff';lines.forEach((line,i)=>ctx.fillText(line,pad,h-box+pad+i*lh))}
async function captureNow(){if(!stream||!preview.videoWidth){showError('Start the live camera first, or use Phone Camera.');return}const loc=await getLocation();canvas.width=preview.videoWidth;canvas.height=preview.videoHeight;const ctx=canvas.getContext('2d'),{b,c,s}=lightValues();ctx.filter=`brightness(${b}) contrast(${c}) saturate(${s})`;ctx.drawImage(preview,0,0,canvas.width,canvas.height);ctx.filter='none';drawStamp(ctx,canvas.width,canvas.height,loc);canvas.toBlob(blob=>{if(blob){addCapture(blob,'photo','jpg');setStatus('Photo captured')}},'image/jpeg',.96)}
async function takePhoto(){if(countdownRunning||!stream)return;countdownRunning=true;[captureBtn,quickCaptureBtn,dockPhoto].forEach(b=>b.disabled=true);try{for(let i=Number(timerSelect.value);i>0;i--){if(!stream)return;countdownEl.hidden=false;countdownEl.textContent=i;setStatus(`Photo in ${i}`);await new Promise(r=>setTimeout(r,1000))}resetCountdown();await captureNow()}finally{resetCountdown();if(stream)[captureBtn,quickCaptureBtn,dockPhoto].forEach(b=>b.disabled=false)}}
function bestMime(){return['video/webm;codecs=vp9,opus','video/webm;codecs=vp8,opus','video/webm','video/mp4'].find(t=>MediaRecorder.isTypeSupported(t))||''}
function setRecordingUI(on){recordingBadge.hidden=!on;recordBtn.textContent=dockVideo.textContent=on?'Stop':'Video';recordBtn.classList.toggle('danger',on);quickRecordBtn.classList.toggle('danger',on);quickRecordBtn.textContent=on?'■':'●'}
function toggleRecording(){if(!stream||typeof MediaRecorder==='undefined')return;if(recorder?.state==='recording'){recorder.stop();return}recordedChunks=[];const mime=bestMime();recorder=new MediaRecorder(stream,mime?{mimeType:mime}:undefined);recorder.ondataavailable=e=>{if(e.data.size)recordedChunks.push(e.data)};recorder.onstop=()=>{const type=recorder.mimeType||'video/webm',ext=type.includes('mp4')?'mp4':'webm';addCapture(new Blob(recordedChunks,{type}),'video',ext);setRecordingUI(false);setStatus('Video saved')};recorder.start(1000);setRecordingUI(true);setStatus('Recording')}
function renderGallery(){gallery.innerHTML='';if(!captures.length){gallery.innerHTML='<p class="gallery-empty">Photos and videos will appear here.</p>';return}captures.forEach((c,i)=>{const card=document.createElement('article');card.className='capture-item';card.innerHTML=`${c.type==='photo'?`<img src="${c.url}" alt="OSKO capture">`:`<video src="${c.url}" controls playsinline></video>`}<div class="capture-actions"><a href="${c.url}" download="${c.filename}">Save</a><button type="button" data-remove="${i}">Delete</button></div>`;gallery.appendChild(card)})}
function bindTap(el,fn){let last=0;el.addEventListener('pointerup',e=>{e.preventDefault();const now=Date.now();if(now-last<350)return;last=now;fn()});el.addEventListener('click',e=>e.preventDefault())}

[[startBtn,startCamera],[dockStart,startCamera],[captureBtn,takePhoto],[quickCaptureBtn,takePhoto],[dockPhoto,takePhoto],[recordBtn,toggleRecording],[quickRecordBtn,toggleRecording],[dockVideo,toggleRecording],[switchBtn,switchCamera],[quickSwitchBtn,switchCamera],[dockSwitch,switchCamera]].forEach(([el,fn])=>bindTap(el,fn));
fullscreenBtn.addEventListener('click',async()=>{try{if(!document.fullscreenElement)await cameraCard.requestFullscreen?.();else await document.exitFullscreen?.()}catch(e){showError('Full screen is not supported by this browser.')}});
brightnessRange.addEventListener('input',updateLight);nightToggle.addEventListener('change',()=>{if(nightToggle.checked&&Number(brightnessRange.value)<185)brightnessRange.value=185;updateLight();setStatus(nightToggle.checked?'Night boost on':'Night boost off')});torchToggle.addEventListener('change',()=>setTorch(torchToggle.checked));gridToggle.addEventListener('change',()=>gridOverlay.hidden=!gridToggle.checked);zoomRange.addEventListener('input',async()=>{zoomValue.textContent=`${Number(zoomRange.value).toFixed(1)}×`;try{await videoTrack?.applyConstraints({advanced:[{zoom:Number(zoomRange.value)}]})}catch{showError('Zoom is not supported by this camera.')}});locationToggle.addEventListener('change',()=>{if(!locationToggle.checked)currentLocation=null});
nativeCapture.addEventListener('change',()=>{const file=nativeCapture.files?.[0];if(!file)return;const type=file.type.startsWith('video/')?'video':'photo',ext=(file.name.split('.').pop()|| (type==='video'?'mp4':'jpg')).toLowerCase();addCapture(file,type,ext);setStatus('Phone camera capture added');nativeCapture.value=''});
clearBtn.addEventListener('click',()=>{captures.forEach(c=>URL.revokeObjectURL(c.url));captures=[];renderGallery()});gallery.addEventListener('click',e=>{const b=e.target.closest('[data-remove]');if(!b)return;const i=Number(b.dataset.remove);URL.revokeObjectURL(captures[i].url);captures.splice(i,1);renderGallery()});
window.addEventListener('beforeunload',()=>stream?.getTracks().forEach(t=>t.stop()));updateLight();setEnabled(false);if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(console.error));
