const $=s=>document.querySelector(s);
const preview=$('#preview'),canvas=$('#canvas'),emptyState=$('#emptyState'),statusEl=$('#status'),gallery=$('#gallery'),errorBox=$('#errorBox');
const startBtn=$('#startBtn'),captureBtn=$('#captureBtn'),recordBtn=$('#recordBtn'),switchBtn=$('#switchBtn'),quickCaptureBtn=$('#quickCaptureBtn'),quickSwitchBtn=$('#quickSwitchBtn'),quickRecordBtn=$('#quickRecordBtn'),quickTorchBtn=$('#quickTorchBtn'),dockStart=$('#dockStart'),dockPhoto=$('#dockPhoto'),dockVideo=$('#dockVideo'),dockSwitch=$('#dockSwitch');
const zoomRange=$('#zoomRange'),zoomValue=$('#zoomValue'),brightnessRange=$('#brightnessRange'),brightnessValue=$('#brightnessValue'),steadyToggle=$('#steadyToggle'),nightToggle=$('#nightToggle'),screenLightToggle=$('#screenLightToggle'),torchToggle=$('#torchToggle'),gridToggle=$('#gridToggle'),stampToggle=$('#stampToggle'),locationToggle=$('#locationToggle'),timerSelect=$('#timerSelect'),modeSelect=$('#modeSelect');
let stream=null,videoTrack=null,facingMode='environment',captures=[],torchOn=false;
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function setStatus(m){if(statusEl)statusEl.textContent=m}
function showError(m=''){if(errorBox){errorBox.hidden=!m;errorBox.textContent=m}}
function setEnabled(on){[captureBtn,quickCaptureBtn,dockPhoto,switchBtn,quickSwitchBtn,dockSwitch].forEach(b=>{if(b)b.disabled=!on});[recordBtn,quickRecordBtn,dockVideo].forEach(b=>{if(b)b.disabled=true});if(startBtn)startBtn.textContent=on?'Stop':'Start';if(dockStart)dockStart.textContent=on?'Stop':'Start'}
function updateVisuals(){if(preview){const b=Number(brightnessRange?.value||100)/100;preview.style.filter=`brightness(${b})`;preview.style.transform=`scale(${steadyToggle?.checked?1.04:1})`}if(brightnessValue)brightnessValue.textContent=`${brightnessRange?.value||100}%`;if(document.body)document.body.classList.toggle('selfie-light',!!screenLightToggle?.checked&&facingMode==='user')}
function setupCapabilities(){videoTrack=stream?.getVideoTracks?.()[0]||null;const caps=videoTrack?.getCapabilities?.()||{},settings=videoTrack?.getSettings?.()||{};if(caps.zoom&&zoomRange){zoomRange.min=caps.zoom.min;zoomRange.max=caps.zoom.max;zoomRange.step=caps.zoom.step||.1;zoomRange.value=settings.zoom||caps.zoom.min;zoomRange.disabled=false}else if(zoomRange){zoomRange.min=zoomRange.max=zoomRange.value=1;zoomRange.disabled=true}if(zoomValue)zoomValue.textContent=`${Number(zoomRange?.value||1).toFixed(1)}×`}
async function stopCamera(){stream?.getTracks?.().forEach(t=>t.stop());stream=null;videoTrack=null;if(preview)preview.srcObject=null;if(emptyState)emptyState.hidden=false;if(zoomRange)zoomRange.disabled=true;setEnabled(false);setStatus('Camera off')}
async function startCamera(){showError('');if(stream){await stopCamera();return}if(!navigator.mediaDevices?.getUserMedia){showError('Live camera is unavailable in this browser.');return}try{setStatus('Opening camera…');stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:facingMode},width:{ideal:1920},height:{ideal:1080}},audio:false});if(preview){preview.srcObject=stream;await preview.play()}if(emptyState)emptyState.hidden=true;setupCapabilities();setEnabled(true);updateVisuals();setStatus('Camera ready')}catch(e){console.error(e);stream=null;setEnabled(false);showError(e?.name==='NotAllowedError'?'Allow camera permission in Chrome, then tap Start Camera again.':'The camera could not start.');setStatus('Camera blocked')}}
async function switchCamera(){if(stream)await stopCamera();facingMode=facingMode==='environment'?'user':'environment';await startCamera()}
function addCapture(blob){const url=URL.createObjectURL(blob),stamp=new Date().toISOString().replace(/[:.]/g,'-');captures.unshift({url,blob,filename:`osko-photo-${stamp}.jpg`});renderGallery()}
function renderGallery(){if(!gallery)return;gallery.innerHTML='';if(!captures.length){gallery.innerHTML='<p class="gallery-empty">Photos and videos will appear here.</p>';return}captures.forEach(c=>{const card=document.createElement('article');card.className='capture-item';card.innerHTML=`<img src="${c.url}" alt="OSKO capture"><a download="${c.filename}" href="${c.url}">Save picture</a>`;gallery.appendChild(card)})}
async function takePhoto(){if(!stream||!preview?.videoWidth){showError('Start the camera first.');return}try{const wait=Number(timerSelect?.value||0);if(wait)await sleep(wait*1000);canvas.width=preview.videoWidth;canvas.height=preview.videoHeight;const ctx=canvas.getContext('2d');ctx.filter=preview.style.filter||'none';ctx.drawImage(preview,0,0,canvas.width,canvas.height);canvas.toBlob(blob=>{if(blob){addCapture(blob);setStatus('Photo captured')}},'image/jpeg',.96)}catch(e){console.error(e);showError('The photo could not be captured.')}}
async function setTorch(on){if(!videoTrack)return;try{await videoTrack.applyConstraints({advanced:[{torch:on}]});torchOn=on;if(torchToggle)torchToggle.checked=on;if(quickTorchBtn)quickTorchBtn.textContent=on?'REAR FLASH ON':'REAR FLASH';setStatus(on?'Rear flash on':'Rear flash off')}catch(e){showError('Rear flash is unavailable in Chrome on this phone.')}}
[startBtn,dockStart].forEach(b=>b?.addEventListener('click',startCamera));[captureBtn,quickCaptureBtn,dockPhoto].forEach(b=>b?.addEventListener('click',takePhoto));[switchBtn,quickSwitchBtn,dockSwitch].forEach(b=>b?.addEventListener('click',switchCamera));brightnessRange?.addEventListener('input',updateVisuals);steadyToggle?.addEventListener('change',updateVisuals);screenLightToggle?.addEventListener('change',updateVisuals);zoomRange?.addEventListener('input',async()=>{if(!videoTrack)return;try{await videoTrack.applyConstraints({advanced:[{zoom:Number(zoomRange.value)}]});if(zoomValue)zoomValue.textContent=`${Number(zoomRange.value).toFixed(1)}×`}catch{}});torchToggle?.addEventListener('change',()=>setTorch(torchToggle.checked));quickTorchBtn?.addEventListener('click',()=>setTorch(!torchOn));
setEnabled(false);updateVisuals();renderGallery();
